table Dim_Date
	lineageTag: 8211b974-e991-4f70-af97-428f136d1df7
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: d94d3fa2-5a8c-4128-a9e6-dad0c904da9c
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: f53de893-d80c-4362-a46d-90613519a409
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: bdec2038-ca91-4383-b9fd-35b6ad433665
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 7eeb147f-0492-48bc-97d2-c04e543ce23e
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: f4abfc71-7661-413e-97c1-a5e9ded303d1
		summarizeBy: none
		sourceColumn: quarter_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 99593c61-769e-41c7-9f1f-0d74dd4e6327
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 8c07ec00-d8e5-4489-b635-c493fe343b69
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column month_short
		dataType: string
		lineageTag: 76b5c311-40c1-4aeb-a1b2-6ed53b2c34f2
		summarizeBy: none
		sourceColumn: month_short

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: a968acff-030d-4fc0-871f-1f1c1867f08d
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: 59c8bd20-69c1-4522-97c7-96f50743aa0f
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: de832e8f-5d03-44b4-b1e0-3c47cf54ff3c
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: ab5ba269-a9d4-4f61-a687-ffc96efc798f
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 278456de-2bfb-4b02-b251-fc526ae28409
		summarizeBy: sum
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 6cb0cf30-63c1-4b92-bc4c-e6a57b0e6427
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "OlistEcommerce"),
				    dbo_Dim_Date = Source{[Schema="dbo",Item="Dim_Date"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Dim_Date,{{"date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
