/*
=============================================================================
 QUERY 1: CUSTOMER VALUE & RETENTION ANALYSIS
 Brazilian E-Commerce (Olist) — Portfolio Project
=============================================================================
 BUSINESS QUESTION:
   What is the quantitative difference between repeat customers and
   one-time buyers? How much more valuable are loyal customers?

 WHY IT MATTERS:
   Customer Acquisition Cost (CAC) is always higher than retention cost.
   If we can prove that repeat customers spend significantly more,
   it justifies shifting marketing budget toward retention programs.

 SQL TECHNIQUES DEMONSTRATED:
   - CTE (Common Table Expression) for clean logical separation
   - COUNT(DISTINCT) for accurate customer counting
   - CASE WHEN for customer segmentation
   - Aggregate functions with GROUP BY
=============================================================================
*/

USE OlistEcommerce;
GO

-- ─────────────────────────────────────────────────────────────
-- STEP 1: Build a CTE that calculates total spend and order count
--         for each UNIQUE customer (using customer_unique_id, not
--         customer_id, because customer_id changes per transaction
--         while customer_unique_id is the TRUE identifier)
-- ─────────────────────────────────────────────────────────────
WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        -- Count distinct orders (not items) to get TRUE purchase frequency
        COUNT(DISTINCT o.order_id)           AS total_orders,
        -- Total monetary value from payments table (most accurate source)
        SUM(p.payment_value)                 AS total_spent,
        -- Track first and last purchase dates for lifecycle analysis
        MIN(o.order_purchase_timestamp)      AS first_purchase,
        MAX(o.order_purchase_timestamp)      AS last_purchase
    FROM orders o
        -- JOIN to customers to get the stable unique ID
        INNER JOIN customers c ON o.customer_id = c.customer_id
        -- JOIN to payments to get monetary values
        INNER JOIN payments p  ON o.order_id    = p.order_id
    WHERE
        -- Only count delivered orders — canceled orders don't generate revenue
        o.order_status = 'delivered'
    GROUP BY
        c.customer_unique_id
),

-- ─────────────────────────────────────────────────────────────
-- STEP 2: Classify each customer as "One-Time" or "Repeat"
--         based on their total order count
-- ─────────────────────────────────────────────────────────────
customer_segments AS (
    SELECT
        customer_unique_id,
        total_orders,
        total_spent,
        first_purchase,
        last_purchase,
        -- Business logic: 1 order = one-time, 2+ orders = repeat/loyal
        CASE
            WHEN total_orders = 1 THEN 'One-Time Customer'
            ELSE 'Repeat Customer'
        END AS customer_segment,
        -- Days between first and last purchase (0 for one-time buyers)
        DATEDIFF(DAY, first_purchase, last_purchase) AS customer_lifespan_days
    FROM customer_orders
)

-- ─────────────────────────────────────────────────────────────
-- STEP 3: Aggregate by segment to compare the two groups
-- ─────────────────────────────────────────────────────────────
SELECT
    customer_segment,
    -- How many customers in each segment
    COUNT(*)                                         AS customer_count,
    -- What percentage of total customers does each segment represent
    CAST(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()
         AS DECIMAL(5,2))                            AS pct_of_total,
    -- Total revenue generated by this segment
    CAST(SUM(total_spent) AS DECIMAL(15,2))          AS total_revenue,
    -- Average revenue per customer (CLV proxy)
    CAST(AVG(total_spent) AS DECIMAL(10,2))          AS avg_revenue_per_customer,
    -- Average number of orders per customer
    CAST(AVG(CAST(total_orders AS FLOAT))
         AS DECIMAL(5,2))                            AS avg_orders_per_customer,
    -- Average lifespan in days (only meaningful for repeat customers)
    CAST(AVG(CAST(customer_lifespan_days AS FLOAT))
         AS DECIMAL(8,1))                            AS avg_lifespan_days
FROM customer_segments
GROUP BY customer_segment
ORDER BY avg_revenue_per_customer DESC;

/*
 EXPECTED INSIGHT:
   Repeat customers (~3% of base) generate ~88% higher avg revenue
   ($302 vs $160 per customer). This proves the business case for
   investing in retention marketing over pure acquisition.

 ACTIONABLE RECOMMENDATION:
   Launch "Welcome Back" marketing automation campaigns targeting the
   ~90,000 one-time buyers to convert them into repeat customers.
   Even a 5% conversion rate would add significant incremental revenue.
*/
